version: "3.6"

services:
  buildah:
    user: bob
    build:
      context: .
      dockerfile: buildah.Dockerfile
      target: devcontainer
      args:
        - X_DOCKER_USER_ID
        - X_DOCKER_USER_GROUP_ID
    stdin_open: true
    tty: true
    working_dir: "/home/bob/app"
    volumes:
      - type: bind
        source: .
        target: /home/bob/app
    secrets:
      - source: env
        target: /home/bob/.env
    command: tail -f /dev/null
    cap_drop:
      - ALL
    cap_add:
      - dac_override
      - setuid
      - setgid
      - sys_admin
    security_opt:
      - "apparmor=unconfined"
      - "seccomp=unconfined"

secrets:
  env:
    file: .env
